#!/bin/bash
KEY=$2
echo "Initialising instance..."
ssh -oStrictHostKeyChecking=no -i $KEY ec2-user@$1 'wget -O - https://gist.githubusercontent.com/HarriBellThomas/22af64d909627b9f7a84f5fecb4da04c/raw/f54623819f07dfd3640d96bfb7e7b496dcc027c8/bubblegum-init.sh | bash' > /dev/null 2>&1
if [ $? -eq 0 ]; then
    echo "Setup, starting application..."
    ssh -oStrictHostKeyChecking=no -i $KEY ec2-user@$1 'docker pull harribellthomas/bubblegum:latest && docker run --rm -itd --network host -e JAVA_OPTS="-Dhttp.port=80 -Dhttps.port=443" --name bubblegum harribellthomas/bubblegum:latest'
    if [ $? -eq 0 ]; then
        echo "Complete."
    else
        echo "Failed stage 2"
    fi
else
    echo "Failed stage 1"
fi
